substitutions:
  name: zb-gw03-coordinator
  device_description: "ZB-GW03 eWeLink Ethernet Zigbee Gateway based Zigbee Coordinator"
  device_role: "coordinator"

packages:
  zb-gw03:
    url: https://github.com/syssi/esphome-zb-gw03
    ref: main
    files:
      - packages/core.yaml
      - packages/ethernet.yaml
      - packages/status_led.yaml
      - packages/green_led.yaml
      - packages/i2c.yaml
      - packages/button_zigbee_reset.yaml
      - packages/mdns.yaml
    refresh: 0s
